export const REQUEST_CITIES = 'REQUEST_CITIES';
export const GET_CITIES = 'GET_CITIES';
export const ERROR_CITIES = 'ERROR_CITIES';

export const REQUEST_ITINERARIES = 'REQUEST_ITINERARIES';
export const GET_ITINERARIES = 'GET_ITINERARIES';
export const ERROR_ITINERARIES = 'ERROR_ITINERARIES';

export const REQUEST_ITINERARIES_COMMENTS = 'REQUEST_ITINERARIES_COMMENTS';
export const GET_ITINERARIES_COMMENTS = 'GET_ITINERARIES_COMMENTS';
export const ERROR_ITINERARIES_COMMENTS = 'ERROR_ITINERARIES_COMMENTS';

export const REQUEST_NEWCOMMENT = 'REQUEST_NEWCOMMENT';
export const POST_NEWCOMMENT = 'POST_NEWCOMMENT';
export const ERROR_NEWCOMMENT = 'ERROR_NEWCOMMENT';

export const REQUEST_ACTIVITIES = 'REQUEST_ACTIVITIES';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const ERROR_ACTIVITIES = 'ERROR_ACTIVITIES';

export const REQUEST_NEWUSER = 'REQUEST_NEWUSER';
export const POST_NEWUSER = 'POST_NEWUSER';
export const ERROR_NEWUSER = 'ERROR_NEWUSER';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const POST_LOGIN = 'POST_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';

export const REQUEST_USERAUTH = 'REQUEST_USERAUTH';
export const POST_USERAUTH = 'POST_USERAUTH';
export const ERROR_USERAUTH = 'ERROR_USERAUTH';

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const EXECUTE_LOGOUT = 'EXECUTE_LOGOUT';
export const ERROR_LOGOUT = 'ERROR_LOGOUT';

export const REQUEST_FAV_ITINERARY = 'REQUEST_FAV_ITINERARY';
export const EXECUTE_FAV_ITINERARY = 'EXECUTE_FAV_ITINERARY';
export const ERROR_FAV_ITINERARY = 'ERROR_FAV_ITINERARY';