export const REQUEST_CITIES = 'REQUEST_CITIES';
export const GET_CITIES = 'GET_CITIES';
export const ERROR_CITIES = 'ERROR_CITIES';

export const REQUEST_ITINERARIES = 'REQUEST_ITINERARIES';
export const GET_ITINERARIES = 'GET_ITINERARIES';
export const ERROR_ITINERARIES = 'ERROR_ITINERARIES';

export const REQUEST_ACTIVITIES = 'REQUEST_ACTIVITIES';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const ERROR_ACTIVITIES = 'ERROR_ACTIVITIES';

export const REQUEST_NEWUSER = 'REQUEST_NEWUSER';
export const POST_NEWUSER = 'POST_NEWUSER';
export const ERROR_NEWUSER = 'ERROR_NEWUSER';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const POST_LOGIN = 'POST_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';

export const REQUEST_USERAUTH = 'REQUEST_USERAUTH';
export const POST_USERAUTH = 'POST_USERAUTH';
export const ERROR_USERAUTH = 'ERROR_USERAUTH';