export const REQUEST_CITIES = 'REQUEST_CITIES';
export const GET_CITIES = 'GET_CITIES';
export const ERROR_CITIES = 'ERROR_CITIES';

export const REQUEST_ITINERARIES = 'REQUEST_ITINERARIES';
export const GET_ITINERARIES = 'GET_ITINERARIES';
export const ERROR_ITINERARIES = 'ERROR_ITINERARIES';

export const REQUEST_ACTIVITIES = 'REQUEST_ACTIVITIES';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const ERROR_ACTIVITIES = 'ERROR_ACTIVITIES';